### PR TITLE
Attempt fix of npm publish error

### PR DESCRIPTION
**Pull request by jonato1**
- Attempt fix of npm publish error (#27)
- Update git workflow to perform npm publish dry run

### CODE REVIEW

**Comment by fjs21** [comment]
Didn’t work unfortunately. Same error. Could you leave type blank on initialization? It passed ‘npm run lint’ on my end if I just removed the object
`private readonly awsKeys`
but I have no way of checking functionality apart from build, which it does.

**Comment by jonato1** [comment]
@fjs21 Sure, let me try and test now. It is odd that you are getting the lint error though, as I am not and it doesn't appear on the Git checks either. https://github.com/fjs21/homebridge-blueair/runs/6329332345?check_suite_focus=true

**Comment by jonato1** [comment]
@fjs21 So it looks like that breaks things. When you are building and trying to publish, are you doing so locally? If so, what commands are you running in what order? For reference, I'm doing:
- npm install
- npm run lint
- npm run build
- npm publish --dry-run

All of which seem to work without any issue. I can keep digging, but I am curious on where the disconnect is as I cannot reproduce the error you are seeing, and the package that I have runs fine locally on my Homebridge.

**Comment by jonato1** [comment]
Hey @fjs21 - just wanted to check in to see if you have any updates. If not, I'll try and dig into this more tonight, but I'm kinda coding in the dark as my ES Lint is not returning the same errors that you're seeing, so I won't know when it's necessarily fixed.

Thanks,
Jon

**Comment by jonato1** [comment]
@fjs21 Awesome - thanks for the update!

**Pull request merged**
